Patching ci/cd pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,6 +30,10 @@ jobs:
               run: docker compose -f docker/ci/docker-compose.ci.yml up -d --build
               working-directory: ${{ github.workspace }}
 
+            - name: Check if .env is mounted correctly inside container
+              run: |
+                  docker compose -f docker/ci/docker-compose.ci.yml exec -T app bash -c "test -f /var/www/html/.env && echo '.env exists ✅' && cat /var/www/html/.env || (echo '❌ .env is missing inside container' && exit 1)"
+
             - name: Wait for MySQL (timeout 60s)
               run: |
                   for i in {1..60}; do
